"""A consolidated CSS link is necessary but not sufficient for certification."""
from hashlib import sha256
import json
from pathlib import Path

import pytest
from engines.canonical_assets import canonical_css_href, template_css_href, source_bundle_valid

VERSION = 'V941_ADMIN_PC_MASTER_CONTROL_CENTER_SHARK_AI_OPERATING_SYSTEM'
HREF = '/static/product-system.css?v=' + VERSION + '-home-leagues-1'
LINK = '<link rel="stylesheet" href="' + HREF + '">'


def test_accepts_canonical_versioned_stylesheet_not_obsolete_layers():
    assert canonical_css_href(LINK, VERSION) == HREF
    assert canonical_css_href(LINK.replace('rel="stylesheet"','rel="preload stylesheet"'), VERSION) == HREF


@pytest.mark.parametrize('markup', ['', '<!--' + LINK + '-->', LINK + LINK,
    LINK.replace('product-system.css', 'app.css'), LINK.replace(VERSION, 'V940'),
    LINK.replace('home-leagues-1', 'x&v=V940'), LINK.replace('href=', 'disabled href='),
    LINK.replace('href=', 'media="print" href='), LINK.replace('/static/', 'https://other.invalid/static/'),
    '<script>"' + LINK + '"</script>', '<p>app.css?v=' + VERSION + '</p>'])
def test_rejects_missing_fake_disabled_duplicate_or_mismatched_links(markup):
    assert canonical_css_href(markup, VERSION) == ''


def test_actual_template_contract_uses_product_bundle():
    root = Path(__file__).resolve().parents[1]
    href = template_css_href((root/'templates/base.html').read_text(), VERSION)
    assert href.startswith('/static/product-system.css?v=' + VERSION)
    assert 'home-leagues' in href


def test_comment_in_template_cannot_supply_missing_link():
    assert template_css_href('{# ' + LINK + ' #}', VERSION) == ''


def test_source_fingerprint_rejects_stale_or_empty_bundle(tmp_path):
    (tmp_path/'tools').mkdir(); (tmp_path/'static').mkdir()
    (tmp_path/'tools/visual_css_sources.json').write_text('["design-system.css"]')
    source = '.league { display: grid; }\n'
    (tmp_path/'static/design-system.css').write_text(source)
    header = '/* Generated by npm run build:css; source-sha256: ' + sha256(source.encode()).hexdigest() + ' */\n'
    bundle = tmp_path/'static/product-system.css'
    bundle.write_text(header + '.league{display:grid}')
    assert source_bundle_valid(tmp_path)
    (tmp_path/'static/design-system.css').write_text('.league{display:flex}')
    assert not source_bundle_valid(tmp_path)
    (tmp_path/'static/design-system.css').write_text(source)
    bundle.write_text(header)
    assert not source_bundle_valid(tmp_path)


@pytest.mark.parametrize('corruption', ['none', 'css-bytes', 'runtime-digest', '404'])
def test_postdeploy_probe_compares_served_css_bytes_to_checkout(monkeypatch, corruption):
    from tools import v937_post_deploy_certification as cert
    from engines.canonical_assets import css_digest
    requests = []
    version = cert.ACTIVE_VERSION
    href = '/static/product-system.css?v=' + version + '-home-leagues-1'
    css = (cert.ROOT/'static/product-system.css').read_text()
    runtime = {'version':version, 'git_commit_hint':'a'*40, 'version_files_match':True,
        'deployment_alignment_status':'aligned_local_files', 'static_css_cache_busting':True,
        'service_worker_cache_name':cert.EXPECTED_CACHE, 'sentinel_active_issues_count':0,
        'canonical_css_sha256': 'wrong' if corruption == 'runtime-digest' else css_digest(cert.ROOT)}
    sports = {'matches':[], 'live':[], 'counts':{'live':0}, 'no_external_calls':True,
        'poll_after_seconds':180, 'last_safe_sync':cert.datetime.now(cert.MADRID).isoformat()}
    def request(base, path, timeout=30):
        requests.append(path)
        payload = {'/api/runtime-version':runtime, '/api/realtime/sports':sports, '/manifest.json':{'name':'QA'}}.get(path)
        body = json.dumps(payload) if payload is not None else '<link rel="stylesheet" href="'+href+'">'
        if path == '/service-worker.js': body = cert.EXPECTED_CACHE
        if path == href: body = css + ('/* wrong */' if corruption == 'css-bytes' else '')
        status = 404 if path == '/ruta-inventada' or (path == href and corruption == '404') else 200
        return {'path':path, 'status':status, 'body':body, 'latency_ms':1, 'final_url':base+path,'error':None}
    monkeypatch.setattr(cert, '_request', request)
    result = cert._probe('https://qa.invalid', 'offline', version, 'a'*40)
    assert href in requests
    if corruption == 'none': assert result['errors'] == []
    else: assert any('css_asset' in error for error in result['errors'])
