from pathlib import Path
import hashlib
import json

from playwright.sync_api import sync_playwright

ROOT = Path(__file__).resolve().parents[1]


def test_semantic_states_survive_the_complete_cascade(app_module):
    template = app_module.app.jinja_env.from_string('''
      {% from 'components/v933_ui.html' import status_chip, empty_state, action_button %}
      {{ status_chip('Confirmado', 'success') }}{{ status_chip('Pendiente', 'warning') }}
      {{ status_chip('Bloqueado', 'danger') }}
      {{ empty_state('Sin datos disponibles', 'Espera a una actualización confirmada.', 'Calendario', '/calendario') }}
      {{ action_button('No disponible', disabled=true) }}
    ''')
    with app_module.app.test_request_context('/'):
        markup = template.render()
    with sync_playwright() as pw:
        browser = pw.chromium.launch()
        page = browser.new_page(viewport={'width': 320, 'height': 740})
        page.set_content('<html><body class="ns-app ns-tier-free" data-v928-shell="true">' + markup + '</body></html>')
        page.add_style_tag(content=(ROOT / 'static/product-system.css').read_text(encoding='utf-8'))
        colors = page.locator('.v933-status-chip').evaluate_all('(els) => els.map(e => getComputedStyle(e).color)')
        assert len(set(colors)) == 3, 'Success, warning and blocked must remain distinct'
        assert page.locator('button:disabled').count() == 1
        assert page.locator('[data-empty-state] a').get_attribute('href') == '/calendario'
        assert page.evaluate('document.documentElement.scrollWidth <= innerWidth + 2')
        page.emulate_media(reduced_motion='reduce')
        duration = page.locator('.v933-action').first.evaluate('(e) => getComputedStyle(e).transitionDuration')
        assert all(float(value.strip().rstrip('s')) < .01 for value in duration.split(','))
        browser.close()


def test_shell_uses_one_consolidated_product_bundle():
    base = (ROOT / 'templates/base.html').read_text(encoding='utf-8')
    assert base.count("filename='product-system.css'") == 1
    assert "filename='app.css'" not in base
    assert 'href="#main-content"' in base
    assert 'id="main-content"' in base


def test_release_validator_rejects_stale_or_incomplete_bundle(tmp_path, monkeypatch):
    from tools import visual_assets
    monkeypatch.setattr(visual_assets, 'ROOT', tmp_path)
    (tmp_path / 'tools').mkdir()
    (tmp_path / 'static').mkdir()
    (tmp_path / 'tools/visual_css_sources.json').write_text(json.dumps(['component.css']))
    content = '.component { color: red; }\n'
    (tmp_path / 'static/component.css').write_text(content)
    digest = hashlib.sha256(content.encode()).hexdigest()
    (tmp_path / 'static/product-system.css').write_text(
        '/* Generated by npm run build:css; source-sha256: ' + digest + ' */\n.component{color:red}')
    assert visual_assets.stylesheet_loaded('product-system.css', 'component.css')
    assert not visual_assets.stylesheet_loaded('product-system.css', 'missing.css')
    (tmp_path / 'static/component.css').write_text('.component { color: blue; }')
    assert not visual_assets.stylesheet_loaded('product-system.css', 'component.css')
