"""One CSS contract shared by runtime diagnostics and post-deploy verification."""
from hashlib import sha256
from html.parser import HTMLParser
import json
from pathlib import Path
import re
from urllib.parse import parse_qs, urlsplit

CSS_PATH = '/static/product-system.css'


class _Stylesheets(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.links = []

    def handle_starttag(self, tag, attrs):
        values = dict(attrs)
        if tag == 'link' and 'stylesheet' in str(values.get('rel') or '').lower().split():
            self.links.append(values)


def canonical_css_href(markup, expected_version):
    """Accept one active, same-origin, versioned canonical link, never comments."""
    parser = _Stylesheets()
    parser.feed(str(markup or ''))
    candidates = []
    for item in parser.links:
        try:
            href = str(item.get('href') or '')
            parsed = urlsplit(href)
            if parsed.path == '/static/app.css':
                return ''  # Do not resurrect the obsolete competing stylesheet.
            if parsed.path != CSS_PATH:
                continue
            candidates.append(item)
            values = parse_qs(parsed.query).get('v', [])
            valid_version = len(values) == 1 and (values[0] == expected_version or values[0].startswith(expected_version + '-'))
            if parsed.scheme or parsed.netloc or parsed.fragment or 'disabled' in item or str(item.get('media') or '').lower() not in {'', 'all', 'screen'} or not valid_version:
                return ''
        except ValueError:
            return ''
    return str(candidates[0]['href']) if len(candidates) == 1 else ''


def template_css_href(source, expected_version):
    """Check the link in the template without rendering a request or its context."""
    source = re.sub(r'{#.*?#}', '', source, flags=re.S)
    source = re.sub(r'''\{\{\s*url_for\(\s*['"]static['"]\s*,\s*filename\s*=\s*['"]product-system\.css['"]\s*\)\s*\}\}''', CSS_PATH, source)
    source = re.sub(r'\{\{\s*app_version\s*\}\}', expected_version, source)
    return canonical_css_href(source, expected_version)


def source_bundle_valid(root):
    """Verify the generated bundle's source fingerprint; no Node at runtime."""
    root = Path(root)
    try:
        names = json.loads((root / 'tools/visual_css_sources.json').read_text(encoding='utf-8'))
        if not isinstance(names, list) or not names or len(names) != len(set(names)):
            return False
        static = (root / 'static').resolve()
        paths = [(static / name).resolve() for name in names]
        if any(path.suffix != '.css' or not path.is_relative_to(static) for path in paths):
            return False
        source = '\n'.join(path.read_text(encoding='utf-8') for path in paths)
        expected = '/* Generated by npm run build:css; source-sha256: ' + sha256(source.encode()).hexdigest() + ' */\n'
        bundle = (static / 'product-system.css').read_text(encoding='utf-8')
        return bundle.startswith(expected) and bool(bundle[len(expected):].strip())
    except (OSError, ValueError, TypeError):
        return False


def css_digest(root):
    try:
        return sha256((Path(root) / 'static/product-system.css').read_bytes()).hexdigest()
    except OSError:
        return ''
