// Preserve the established cascade while removing redundant rules and declarations.
// Runtime needs no Node installation: the verified bundle is committed.
import fs from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import crypto from 'node:crypto';
import postcss from 'postcss';
import cssnano from 'cssnano';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const sources = JSON.parse(await fs.readFile(path.join(root, 'tools/visual_css_sources.json'), 'utf8'));
const input = (await Promise.all(sources.map(async file =>
  (await fs.readFile(path.join(root, 'static', file), 'utf8')).replace(/\r\n/g, '\n')
))).join('\n');
const result = await postcss([cssnano({preset: ['default', {
  // Keep custom-property values, animation names and fallback declarations intact.
  reduceIdents: false, mergeIdents: false, discardUnused: false,
  normalizeUrl: false, calc: false
}]})]).process(input, {from: undefined});
const hash = crypto.createHash('sha256').update(input).digest('hex');
const output = `/* Generated by npm run build:css; source-sha256: ${hash} */\n${result.css}\n`;
const target = path.join(root, 'static', 'product-system.css');
if (process.argv.includes('--check')) {
  if ((await fs.readFile(target, 'utf8')).replace(/\r\n/g, '\n') !== output) throw new Error('Visual bundle is stale; run npm run build:css');
} else {
  await fs.writeFile(target, output);
}
console.log(JSON.stringify({sources: sources.length, before: Buffer.byteLength(input), after: Buffer.byteLength(output), sourceSha256: hash}));
