"""Validate source-backed global styles without requiring Node at runtime."""
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def stylesheet_loaded(base_source, asset):
    if base_source.count(asset) == 1:
        return True
    if base_source.count('product-system.css') != 1:
        return False
    sources = json.loads((ROOT / 'tools/visual_css_sources.json').read_text(encoding='utf-8'))
    origins_path = ROOT / 'tools/visual_css_origins.json'
    origins = json.loads(origins_path.read_text(encoding='utf-8')) if origins_path.exists() else {}
    owner = origins.get(asset, asset)
    if owner not in sources or len(sources) != len(set(sources)):
        return False
    content = '\n'.join((ROOT / 'static' / name).read_text(encoding='utf-8') for name in sources)
    digest = hashlib.sha256(content.encode('utf-8')).hexdigest()
    bundle = (ROOT / 'static/product-system.css').read_text(encoding='utf-8')
    return bundle.startswith('/* Generated by npm run build:css; source-sha256: ' + digest + ' */')
